package com.motiva.main;

import com.motiva.db.ConexaoBD;
import java.sql.*;

public class Main {
    public static void main(String[] args) {
        try (Connection conn = ConexaoBD.getInstancia().conectar();
             Statement stmt = conn.createStatement()) {

            System.out.println("Criando tabelas...");

            try {
                stmt.execute("CREATE TABLE EquipeManutencao (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "nome VARCHAR2(100) NOT NULL, " +
                        "especialidade VARCHAR2(50))");
                System.out.println("OK - EquipeManutencao criada.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) System.out.println("EquipeManutencao ja existe.");
                else throw e;
            }

            try {
                stmt.execute("CREATE TABLE TrechoRodovia (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "rodovia VARCHAR2(50), " +
                        "km_inicial NUMBER, " +
                        "km_final NUMBER, " +
                        "nivel_risco VARCHAR2(20))");
                System.out.println("OK - TrechoRodovia criada.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) System.out.println("TrechoRodovia ja existe.");
                else throw e;
            }

            try (PreparedStatement pstmt = conn.prepareStatement(
                    "INSERT INTO EquipeManutencao (nome, especialidade) VALUES (?, ?)")) {
                pstmt.setString(1, "Equipe Alpha");
                pstmt.setString(2, "Rocada");
                pstmt.executeUpdate();
                System.out.println("OK - Equipe inserida!");
            }

            System.out.println("--- Lista de Equipes ---");
            try (ResultSet rs = stmt.executeQuery("SELECT * FROM EquipeManutencao ORDER BY id")) {
                while (rs.next()) {
                    System.out.println("ID: " + rs.getInt("id") +
                            " | Nome: " + rs.getString("nome") +
                            " | Esp: " + rs.getString("especialidade"));
                }
            }

            System.out.println("PIPELINE COMPLETO FUNCIONANDO!");

        } catch (Exception e) {
            System.err.println("Erro: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
